version: "3"

services:
  node:
    build: .
    ports:
      - "9000:9000"  # vue serve
      - "8000:8000"  # vue gui
      - "4321:4321"  # mockサーバー
    volumes:
      - ./app:/app:cached
    tty: true
